import pandas as pd
df = pd.read_csv('Data/Processed/customeriq_powerbi_dataset.csv')
print(f'Total Rows: {len(df)}')
print(f'\nColumn Names & Types:')
print(df.dtypes)
print(f'\nUnique Customers: {df["customer_id"].nunique()}')
print(f'Duplicate Customer IDs: {df["customer_id"].duplicated().sum()}')
print(f'\nNull Values:')
print(df.isnull().sum())
print(f'\nRisk Segment Distribution:')
print(df['risk_segment'].value_counts().sort_index())
print(f'\nChurn Probability Stats:')
print(df['churn_probability'].describe())
print(f'\nMonetary Stats:')
print(df['monetary'].describe())
